FROM golang:1.12 as builder
ENV GO111MODULE=on

WORKDIR /go/src/github.com/k-yomo/elastic_blog_search

RUN apk add --no-cache ca-certificates && update-ca-certificates
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN make build

FROM alpine
COPY --from=builder /go/src/github.com/k-yomo/elastic_blog_search/bin/server /server
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
EXPOSE 1323
ENTRYPOINT ["/server"]