FROM golang:1.13-alpine as builder
ENV GO111MODULE=on

WORKDIR /go/src/github.com/k-yomo/elastic_blog_search

RUN apk add --no-cache ca-certificates && update-ca-certificates
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o bin/server -ldflags "-w -s" ./src/cmd/server

FROM scratch
COPY --from=builder /go/src/github.com/k-yomo/elastic_blog_search/bin/server /server
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
EXPOSE 1323
ENTRYPOINT ["/server", "-domain=0.0.0.0"]