FROM golang:1.13-alpine
ENV GO111MODULE=on

WORKDIR /go/src/github.com/k-yomo/elastic_blog_search

COPY go.mod .
COPY go.sum .
RUN go mod download
RUN go get gopkg.in/urfave/cli.v2@master && go get github.com/oxequa/realize
COPY . .
COPY .realize.yaml .

ENTRYPOINT ["realize", "start", "--server"]
