settings:
  legacy:
    force: false
    interval: 0s

schema:
  - name: elastic_blog_search
    path: src/cmd/server
    commands:
      run:
        status: true
    watcher:
      extensions:
        - go
      paths:
        - ../../