version: '3.7'
services:
  elasticsearch:
    build: ./docker/es
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - XPACK_SECURITY_ENABLED=false

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile-dev
    volumes:
      - .:/go/src/github.com/k-yomo/elastic_blog_search
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  es_data:
