version: '3'
services:
  es:
    build: ./docker/es
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - 5601:5601
    depends_on:
      - es

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile-dev
    ports:
      - 1323:1323
    depends_on:
      - es

volumes:
  es_data:
