swagger: "2.0"
info:
  title: Blog Posts Search Service
  description: HTTP service for blog posts search
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /posts/bulk:
    post:
      tags:
      - register
      summary: register register
      operationId: register#register
      parameters:
      - name: array
        in: body
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/PostRequestBody'
          minItems: 1
      responses:
        "201":
          description: Created response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
  /posts/search:
    get:
      tags:
      - search
      summary: search search
      operationId: search#search
      parameters:
      - name: query
        in: query
        description: search query
        required: true
        type: string
      - name: page
        in: query
        description: page
        required: false
        type: integer
      - name: pageSize
        in: query
        description: results per page
        required: false
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SearchPostResponseCollection'
      schemes:
      - http
  /swagger.json:
    get:
      summary: Download ../gen/http/openapi.json
      operationId: openapi#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  PostRequestBody:
    title: PostRequestBody
    type: object
    properties:
      body:
        type: string
        description: Post's body
        example: A hic delectus sit animi velit unde.
      description:
        type: string
        description: Post's description
        example: Ea esse corrupti molestiae.
      id:
        type: string
        description: Post's id
        example: A blanditiis sed et animi est.
      title:
        type: string
        description: Post's title
        example: Eos minus.
    example:
      body: Et non.
      description: Quia sit porro.
      id: Est autem.
      title: Perspiciatis necessitatibus ab dolor.
  PostResponse:
    title: 'Mediatype identifier: application/vnd.searchresult; view=default'
    type: object
    properties:
      description:
        type: string
        description: Post's description
        example: Perferendis blanditiis.
      id:
        type: string
        description: Post's id
        example: Nostrum nobis ratione rerum corrupti ipsam.
      title:
        type: string
        description: Post's title
        example: Quia suscipit aut.
    description: PostResponse result type (default view)
    example:
      description: Non sunt architecto unde et ea facilis.
      id: Quo aliquam repudiandae et enim et.
      title: Ut sequi est qui omnis.
    required:
    - id
    - title
    - description
  SearchPostResponseCollection:
    title: 'Mediatype identifier: application/vnd.searchresult; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/PostResponse'
    description: SearchResponseBody is the result type for an array of PostResponse
      (default view)
    example:
    - description: Libero sint voluptatem voluptatem possimus.
      id: Voluptatem est ipsa laboriosam assumenda veritatis.
      title: Ullam pariatur debitis asperiores quasi aut tenetur.
    - description: Libero sint voluptatem voluptatem possimus.
      id: Voluptatem est ipsa laboriosam assumenda veritatis.
      title: Ullam pariatur debitis asperiores quasi aut tenetur.
    - description: Libero sint voluptatem voluptatem possimus.
      id: Voluptatem est ipsa laboriosam assumenda veritatis.
      title: Ullam pariatur debitis asperiores quasi aut tenetur.
