swagger: "2.0"
info:
  title: Blog Posts Search Service
  description: HTTP service for blog posts search
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /posts/bulk:
    post:
      tags:
      - register
      summary: register register
      operationId: register#register
      parameters:
      - name: array
        in: body
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/PostRequestBody'
          minItems: 1
      responses:
        "201":
          description: Created response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
  /posts/search:
    get:
      tags:
      - search
      summary: search search
      operationId: search#search
      parameters:
      - name: query
        in: query
        description: search query
        required: true
        type: string
      - name: page
        in: query
        description: page
        required: false
        type: integer
      - name: pageSize
        in: query
        description: results per page
        required: false
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SearchSearchResponseBody'
            required:
            - posts
            - page
            - totalPage
      schemes:
      - http
  /swagger.json:
    get:
      summary: Download ../gen/http/openapi.json
      operationId: openapi#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  PostRequestBody:
    title: PostRequestBody
    type: object
    properties:
      body:
        type: string
        description: Post's body
        example: Veritatis omnis.
      description:
        type: string
        description: Post's description
        example: Consequatur sit quis repellendus.
      id:
        type: string
        description: Post's id
        example: Voluptatibus corrupti possimus.
      title:
        type: string
        description: Post's title
        example: Molestiae nemo quo enim corrupti quasi.
    example:
      body: Hic delectus sit animi velit unde.
      description: Corrupti molestiae sequi.
      id: Blanditiis sed et animi est architecto.
      title: Minus quam ea.
  PostResponseBody:
    title: 'Mediatype identifier: application/vnd.posts; view=default'
    type: object
    properties:
      description:
        type: string
        description: Post's description
        example: Quia sit porro.
      id:
        type: string
        description: Post's id
        example: Est autem.
      title:
        type: string
        description: Post's title
        example: Perspiciatis necessitatibus ab dolor.
    description: PostResponseBody result type (default view)
    example:
      description: Quia suscipit aut.
      id: Et non.
      title: Nostrum nobis ratione rerum corrupti ipsam.
    required:
    - id
    - title
    - description
  PostResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.posts; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/PostResponseBody'
    description: PostCollectionResponseBody is the result type for an array of PostResponseBody
      (default view)
    example:
    - description: Tenetur autem libero sint voluptatem.
      id: Est ipsa laboriosam assumenda veritatis sapiente ullam.
      title: Debitis asperiores quasi.
    - description: Tenetur autem libero sint voluptatem.
      id: Est ipsa laboriosam assumenda veritatis sapiente ullam.
      title: Debitis asperiores quasi.
    - description: Tenetur autem libero sint voluptatem.
      id: Est ipsa laboriosam assumenda veritatis sapiente ullam.
      title: Debitis asperiores quasi.
    - description: Tenetur autem libero sint voluptatem.
      id: Est ipsa laboriosam assumenda veritatis sapiente ullam.
      title: Debitis asperiores quasi.
  SearchSearchResponseBody:
    title: SearchSearchResponseBody
    type: object
    properties:
      page:
        type: integer
        example: 2817857733486969668
        format: int64
      posts:
        $ref: '#/definitions/PostResponseBodyCollection'
      totalPage:
        type: integer
        example: 2385856216989013136
        format: int64
    example:
      page: 11953625375194037860
      posts:
      - description: Tenetur autem libero sint voluptatem.
        id: Est ipsa laboriosam assumenda veritatis sapiente ullam.
        title: Debitis asperiores quasi.
      - description: Tenetur autem libero sint voluptatem.
        id: Est ipsa laboriosam assumenda veritatis sapiente ullam.
        title: Debitis asperiores quasi.
      - description: Tenetur autem libero sint voluptatem.
        id: Est ipsa laboriosam assumenda veritatis sapiente ullam.
        title: Debitis asperiores quasi.
      totalPage: 6673844434372774317
    required:
    - posts
    - page
    - totalPage
