swagger: "2.0"
info:
  title: Blog Posts Search Service
  description: HTTP service for blog posts search
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /posts/bulk:
    post:
      tags:
      - register
      summary: register register
      operationId: register#register
      parameters:
      - name: array
        in: body
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/PostRequestBody'
          minItems: 1
      responses:
        "201":
          description: Created response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
  /swagger.json:
    get:
      summary: Download ../gen/http/openapi.json
      operationId: openapi#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  PostRequestBody:
    title: PostRequestBody
    type: object
    properties:
      body:
        type: string
        description: Post's body
        example: Cumque voluptatem aut facere quia ipsum.
      description:
        type: string
        description: Post's description
        example: Exercitationem tempore.
      id:
        type: string
        description: Post's id
        example: Rerum assumenda nesciunt.
      title:
        type: string
        description: Post's title
        example: Quasi voluptates.
    example:
      body: Debitis asperiores quasi.
      description: Ipsa laboriosam assumenda veritatis sapiente ullam.
      id: Repellat nostrum autem.
      title: Ipsam nemo voluptatem.
    required:
    - id
    - title
    - description
    - body
