swagger: "2.0"
info:
  title: Blog Posts Search Service
  description: HTTP service for blog posts search
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /posts/bulk:
    post:
      tags:
      - posts
      summary: register posts
      description: registers blog posts to be searched
      operationId: posts#register
      parameters:
      - name: Authorization
        in: header
        description: API key used to perform authorization
        required: true
        type: string
      - name: RegisterRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PostsRegisterRequestBody'
          required:
          - posts
      responses:
        "201":
          description: Created response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
      security:
      - api_key_header_Authorization: []
  /posts/search:
    get:
      tags:
      - posts
      summary: search posts
      description: search blog posts
      operationId: posts#search
      parameters:
      - name: query
        in: query
        description: search query
        required: true
        type: string
      - name: page
        in: query
        description: page
        required: false
        type: integer
        default: 1
      - name: pageSize
        in: query
        description: results per page
        required: false
        type: integer
        default: 50
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PostsSearchResponseBody'
            required:
            - posts
            - page
            - totalPage
      schemes:
      - http
  /swagger.json:
    get:
      summary: Download ../gen/http/openapi.json
      operationId: openapi#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  PostOutputResponseBody:
    title: 'Mediatype identifier: application/vnd.posts; view=default'
    type: object
    properties:
      description:
        type: string
        description: Post's description
        example: Corrupti ipsam reprehenderit.
      id:
        type: string
        description: Post's id
        example: Porro repellendus et.
      title:
        type: string
        description: Post's title
        example: Nisi nostrum nobis ratione.
    description: PostOutputResponseBody result type (default view)
    example:
      description: Et omnis ut sequi est qui omnis.
      id: Suscipit aut sit perferendis blanditiis ea quo.
      title: Repudiandae et.
    required:
    - id
    - title
    - description
  PostOutputResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.posts; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/PostOutputResponseBody'
    description: PostOutputCollectionResponseBody is the result type for an array
      of PostOutputResponseBody (default view)
    example:
    - description: Possimus harum molestiae nemo quo enim.
      id: Asperiores quasi aut tenetur autem libero sint.
      title: Voluptatem possimus illo voluptatibus.
    - description: Possimus harum molestiae nemo quo enim.
      id: Asperiores quasi aut tenetur autem libero sint.
      title: Voluptatem possimus illo voluptatibus.
    - description: Possimus harum molestiae nemo quo enim.
      id: Asperiores quasi aut tenetur autem libero sint.
      title: Voluptatem possimus illo voluptatibus.
  PostParamsRequestBody:
    title: PostParamsRequestBody
    type: object
    properties:
      body:
        type: string
        description: Post's body
        example: Minus quam ea.
      description:
        type: string
        description: Post's description
        example: Blanditiis sed et animi est architecto.
      id:
        type: string
        description: Post's id
        example: Consequatur sit quis repellendus.
      title:
        type: string
        description: Post's title
        example: Veritatis omnis.
    example:
      body: Perspiciatis necessitatibus ab dolor.
      description: Est autem.
      id: Corrupti molestiae sequi.
      title: Hic delectus sit animi velit unde.
  PostsRegisterRequestBody:
    title: PostsRegisterRequestBody
    type: object
    properties:
      posts:
        type: array
        items:
          $ref: '#/definitions/PostParamsRequestBody'
        example:
        - body: Repellat nostrum autem.
          description: Cumque voluptatem aut facere quia ipsum.
          id: Quasi voluptates.
          title: Exercitationem tempore.
        minItems: 1
    example:
      posts:
      - body: Repellat nostrum autem.
        description: Cumque voluptatem aut facere quia ipsum.
        id: Quasi voluptates.
        title: Exercitationem tempore.
    required:
    - posts
  PostsSearchResponseBody:
    title: PostsSearchResponseBody
    type: object
    properties:
      page:
        type: integer
        example: 9133816778920279665
        format: int64
      posts:
        $ref: '#/definitions/PostOutputResponseBodyCollection'
      totalPage:
        type: integer
        example: 3659491618346060683
        format: int64
    example:
      page: 9617362754030863365
      posts:
      - description: Possimus harum molestiae nemo quo enim.
        id: Asperiores quasi aut tenetur autem libero sint.
        title: Voluptatem possimus illo voluptatibus.
      - description: Possimus harum molestiae nemo quo enim.
        id: Asperiores quasi aut tenetur autem libero sint.
        title: Voluptatem possimus illo voluptatibus.
      - description: Possimus harum molestiae nemo quo enim.
        id: Asperiores quasi aut tenetur autem libero sint.
        title: Voluptatem possimus illo voluptatibus.
      - description: Possimus harum molestiae nemo quo enim.
        id: Asperiores quasi aut tenetur autem libero sint.
        title: Voluptatem possimus illo voluptatibus.
      totalPage: 4543024737980907117
    required:
    - posts
    - page
    - totalPage
securityDefinitions:
  api_key_header_Authorization:
    type: apiKey
    description: secret api key for authentication
    name: Authorization
    in: header
