swagger: "2.0"
info:
  title: Blog Posts Search Service
  description: HTTP service for blog posts search
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /posts/bulk:
    post:
      tags:
      - register
      summary: register register
      operationId: register#register
      parameters:
      - name: Authorization
        in: header
        description: API key used to perform authorization
        required: true
        type: string
      - name: RegisterRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/RegisterRegisterRequestBody'
          required:
          - posts
      responses:
        "201":
          description: Created response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
      security:
      - api_key_header_Authorization: []
  /posts/search:
    get:
      tags:
      - search
      summary: search search
      operationId: search#search
      parameters:
      - name: query
        in: query
        description: search query
        required: true
        type: string
      - name: page
        in: query
        description: page
        required: false
        type: integer
        default: 1
      - name: pageSize
        in: query
        description: results per page
        required: false
        type: integer
        default: 50
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SearchSearchResponseBody'
            required:
            - posts
            - page
            - totalPage
      schemes:
      - http
  /swagger.json:
    get:
      summary: Download ../gen/http/openapi.json
      operationId: openapi#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  PostRequestBody:
    title: PostRequestBody
    type: object
    properties:
      body:
        type: string
        description: Post's body
        example: Minus quam ea.
      description:
        type: string
        description: Post's description
        example: Blanditiis sed et animi est architecto.
      id:
        type: string
        description: Post's id
        example: Consequatur sit quis repellendus.
      title:
        type: string
        description: Post's title
        example: Veritatis omnis.
    example:
      body: Perspiciatis necessitatibus ab dolor.
      description: Est autem.
      id: Corrupti molestiae sequi.
      title: Hic delectus sit animi velit unde.
  PostResponseBody:
    title: 'Mediatype identifier: application/vnd.posts; view=default'
    type: object
    properties:
      description:
        type: string
        description: Post's description
        example: Corrupti ipsam reprehenderit.
      id:
        type: string
        description: Post's id
        example: Porro repellendus et.
      title:
        type: string
        description: Post's title
        example: Nisi nostrum nobis ratione.
    description: PostResponseBody result type (default view)
    example:
      description: Et omnis ut sequi est qui omnis.
      id: Suscipit aut sit perferendis blanditiis ea quo.
      title: Repudiandae et.
    required:
    - id
    - title
    - description
  PostResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.posts; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/PostResponseBody'
    description: PostCollectionResponseBody is the result type for an array of PostResponseBody
      (default view)
    example:
    - description: Possimus harum molestiae nemo quo enim.
      id: Aut tenetur autem libero.
      title: Voluptatem voluptatem possimus illo voluptatibus.
    - description: Possimus harum molestiae nemo quo enim.
      id: Aut tenetur autem libero.
      title: Voluptatem voluptatem possimus illo voluptatibus.
    - description: Possimus harum molestiae nemo quo enim.
      id: Aut tenetur autem libero.
      title: Voluptatem voluptatem possimus illo voluptatibus.
  RegisterRegisterRequestBody:
    title: RegisterRegisterRequestBody
    type: object
    properties:
      posts:
        type: array
        items:
          $ref: '#/definitions/PostRequestBody'
        example:
        - body: Tempore voluptas cumque voluptatem aut facere.
          description: Assumenda nesciunt nesciunt quasi voluptates perferendis.
          id: Earum dolores qui.
          title: Dolores alias incidunt sunt ut veniam.
        minItems: 1
    example:
      posts:
      - body: Tempore voluptas cumque voluptatem aut facere.
        description: Assumenda nesciunt nesciunt quasi voluptates perferendis.
        id: Earum dolores qui.
        title: Dolores alias incidunt sunt ut veniam.
    required:
    - posts
  SearchSearchResponseBody:
    title: SearchSearchResponseBody
    type: object
    properties:
      page:
        type: integer
        example: 9133816778920279665
        format: int64
      posts:
        $ref: '#/definitions/PostResponseBodyCollection'
      totalPage:
        type: integer
        example: 3659491618346060683
        format: int64
    example:
      page: 9617362754030863365
      posts:
      - description: Possimus harum molestiae nemo quo enim.
        id: Aut tenetur autem libero.
        title: Voluptatem voluptatem possimus illo voluptatibus.
      - description: Possimus harum molestiae nemo quo enim.
        id: Aut tenetur autem libero.
        title: Voluptatem voluptatem possimus illo voluptatibus.
      totalPage: 4543024737980907117
    required:
    - posts
    - page
    - totalPage
securityDefinitions:
  api_key_header_Authorization:
    type: apiKey
    description: secret api key for authentication
    name: Authorization
    in: header
